JVKP/src/objects/Duplicate_Account__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MD_Relation_with_Account__c</fullName>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Duplicate Accounts</relationshipLabel>
        <relationshipName>Duplicate_Accounts</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Duplicate Account</label>
    <nameField>
        <label>Duplicate Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Duplicate Accounts</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

firstproj/src/classes/createrecordsbatchTest.cls
@isTest
Private class createrecordsbatchTest
{

 static testmethod void myunittest1()
  {
  
  Account acc =new Account();
  acc.name = 'vaibhavkiran2';
  insert acc;
  
  list<duplicate_account__c> dacc=new list<duplicate_account__c>();
  duplicate_account__c dup=new duplicate_account__c ();
  dup.MD_Relation_with_Account__c=acc.id;
  dup.date__c=system.today();
  dacc.add(dup);
  insert dacc;
  
  createrecordsbatch cb=new createrecordsbatch ();
  database.executebatch(cb);
  
 }
}